import { MenuItem } from './types';

export const MENU_ITEMS: MenuItem[] = [
  // Appetizers
  {
    id: '1',
    name: 'Beluga Caviar Service',
    description: 'Premium caviar served with blini and crème fraîche',
    price: 48,
    image: '/menu-items/caviar.png',
    category: 'appetizer',
    prepTime: 5,
    dietary: ['gluten-free'],
    spiceLevel: 0,
    available: true,
  },
  {
    id: '2',
    name: 'Fresh Oysters',
    description: 'Selection of fresh oysters on ice with mignonette sauce and lemon',
    price: 18,
    image: '/menu-items/oysters.png',
    category: 'appetizer',
    prepTime: 3,
    dietary: ['gluten-free', 'pescatarian'],
    spiceLevel: 0,
    available: true,
  },
  {
    id: '3',
    name: 'Pan-Seared Foie Gras',
    description: 'Terrine with fig compote and brioche toast',
    price: 24,
    image: '/menu-items/foie-gras.png',
    category: 'appetizer',
    prepTime: 8,
    dietary: [],
    spiceLevel: 0,
    available: true,
  },
  {
    id: '4',
    name: 'Burrata & Heirloom Tomatoes',
    description: 'Creamy burrata cheese with seasonal heirloom tomatoes, fresh basil, and aged balsamic',
    price: 14,
    image: '/menu-items/burrata.png',
    category: 'appetizer',
    prepTime: 5,
    dietary: ['vegetarian', 'gluten-free'],
    spiceLevel: 0,
    available: true,
  },
  {
    id: '5',
    name: 'Spiced Tuna Tartare',
    description: 'Premium sushi-grade tuna with ginger, chili, soy, and crispy wonton chips',
    price: 16,
    image: '/menu-items/tuna.png',
    category: 'appetizer',
    prepTime: 8,
    dietary: ['gluten-free'],
    spiceLevel: 2,
    available: true,
  },
  {
    id: '6',
    name: 'Prime Beef Tartare',
    description: 'Beef tartare with quail egg yolk, capers, shallots, and Dijon mustard',
    price: 18,
    image: '/menu-items/beef-tartare.png',
    category: 'appetizer',
    prepTime: 8,
    dietary: ['gluten-free'],
    spiceLevel: 1,
    available: true,
  },
  {
    id: '7',
    name: 'Crab Bisque',
    description: 'Silky soup with fresh crab meat, crème fraîche, and chive oil',
    price: 14,
    image: '/menu-items/crab-bisque.png',
    category: 'appetizer',
    prepTime: 10,
    dietary: ['gluten-free'],
    spiceLevel: 0,
    available: true,
  },
  {
    id: '8',
    name: 'French Onion Soup',
    description: 'Classic soup with gruyère cheese crust and beef broth',
    price: 12,
    image: '/menu-items/french-onion-soup.png',
    category: 'appetizer',
    prepTime: 12,
    dietary: ['vegetarian'],
    spiceLevel: 0,
    available: true,
  },

  // Main Courses
  {
    id: '9',
    name: 'A5 Wagyu Beef',
    description: 'Premium Japanese wagyu with ponzu sauce, sesame oil, and microgreens',
    price: 58,
    image: '/menu-items/wagyu.png',
    category: 'main',
    prepTime: 18,
    dietary: ['gluten-free'],
    spiceLevel: 0,
    available: true,
  },
  {
    id: '10',
    name: 'Prime Ribeye Steak',
    description: 'Prime grade ribeye with bone marrow butter, roasted garlic, and charred broccolini',
    price: 44,
    image: '/menu-items/ribeye.png',
    category: 'main',
    prepTime: 20,
    dietary: ['gluten-free'],
    spiceLevel: 0,
    available: true,
  },
  {
    id: '11',
    name: 'Beef Wellington',
    description: 'Tender beef tenderloin wrapped in mushroom duxelle and puff pastry, with red wine reduction',
    price: 35,
    image: '/menu-items/wellington.png',
    category: 'main',
    prepTime: 25,
    dietary: [],
    spiceLevel: 0,
    available: true,
  },
  {
    id: '12',
    name: 'Pan-Seared Duck Breast',
    description: 'Crispy skin duck with cherry gastrique, parsnip puree, and sautéed mushrooms',
    price: 32,
    image: '/menu-items/duck-breast.png',
    category: 'main',
    prepTime: 22,
    dietary: ['gluten-free'],
    spiceLevel: 0,
    available: true,
  },
  {
    id: '13',
    name: 'Herb-Crusted Lamb Chops',
    description: 'With rosemary jus, roasted root vegetables, and truffle mashed potatoes',
    price: 38,
    image: '/menu-items/lamb-chops.png',
    category: 'main',
    prepTime: 20,
    dietary: ['gluten-free'],
    spiceLevel: 0,
    available: true,
  },
  {
    id: '14',
    name: 'Maine Lobster Thermidor',
    description: 'Lobster tail with brandy cream sauce, asparagus, and hollandaise',
    price: 42,
    image: '/menu-items/lobster.png',
    category: 'main',
    prepTime: 18,
    dietary: ['gluten-free', 'pescatarian'],
    spiceLevel: 0,
    available: true,
  },
  {
    id: '15',
    name: 'Pan-Seared Salmon',
    description: 'Atlantic salmon fillet with lemon butter sauce, asparagus, and roasted potatoes',
    price: 28,
    image: '/menu-items/salmon.png',
    category: 'main',
    prepTime: 20,
    dietary: ['gluten-free', 'pescatarian'],
    spiceLevel: 0,
    available: true,
  },
  {
    id: '16',
    name: 'Miso-Glazed Black Cod',
    description: 'With bok choy, shiitake mushrooms, and ginger broth',
    price: 30,
    image: '/menu-items/miso-black-cod.png',
    category: 'main',
    prepTime: 18,
    dietary: ['gluten-free', 'pescatarian'],
    spiceLevel: 1,
    available: true,
  },
  {
    id: '17',
    name: 'Whole Grilled Branzino',
    description: 'Fresh Mediterranean fish with lemon, herbs, and seasonal vegetables',
    price: 32,
    image: '/menu-items/branzino.png',
    category: 'main',
    prepTime: 20,
    dietary: ['gluten-free', 'pescatarian'],
    spiceLevel: 0,
    available: true,
  },
  {
    id: '18',
    name: 'Pan-Seared Halibut',
    description: 'White fish with brown butter, capers, and seasonal vegetables',
    price: 28,
    image: '/menu-items/halibut.png',
    category: 'main',
    prepTime: 18,
    dietary: ['gluten-free', 'pescatarian'],
    spiceLevel: 0,
    available: true,
  },
  {
    id: '19',
    name: 'Seared Diver Scallops',
    description: 'With brown butter, crispy sage, and cauliflower puree',
    price: 36,
    image: '/menu-items/scallops.png',
    category: 'main',
    prepTime: 16,
    dietary: ['gluten-free', 'pescatarian'],
    spiceLevel: 0,
    available: true,
  },
  {
    id: '20',
    name: 'Lobster-Filled Ravioli',
    description: 'In saffron beurre blanc with crispy sage',
    price: 28,
    image: '/menu-items/lobster-ravioli.png',
    category: 'main',
    prepTime: 14,
    dietary: ['pescatarian'],
    spiceLevel: 0,
    available: true,
  },
  {
    id: '21',
    name: 'Truffle Risotto',
    description: 'Creamy Arborio risotto with black truffle, parmesan, and wild mushrooms',
    price: 22,
    image: '/menu-items/risotto.png',
    category: 'main',
    prepTime: 18,
    dietary: ['vegetarian', 'gluten-free'],
    spiceLevel: 0,
    available: true,
  },
  {
    id: '22',
    name: 'Porcini Mushroom Risotto',
    description: 'Creamy risotto with aged parmesan and truffle oil',
    price: 20,
    image: '/menu-items/porcini-risotto.png',
    category: 'main',
    prepTime: 18,
    dietary: ['vegetarian', 'gluten-free'],
    spiceLevel: 0,
    available: true,
  },
  {
    id: '23',
    name: 'Wild Mushroom Tagliatelle',
    description: 'Pasta with garlic, sage, truffle oil, and parmesan',
    price: 18,
    image: '/menu-items/mushroom-pasta.png',
    category: 'main',
    prepTime: 14,
    dietary: ['vegetarian'],
    spiceLevel: 0,
    available: true,
  },
  {
    id: '24',
    name: 'Seasonal Vegetable Tart',
    description: 'With goat cheese, pine nuts, and herb oil',
    price: 16,
    image: '/menu-items/vegetable-tart.png',
    category: 'main',
    prepTime: 15,
    dietary: ['vegetarian', 'gluten-free'],
    spiceLevel: 0,
    available: true,
  },

  // Desserts
  {
    id: '25',
    name: 'Chocolate Lava Cake',
    description: 'Warm chocolate cake with molten center, vanilla ice cream, and raspberry coulis',
    price: 12,
    image: '/menu-items/lava-cake.png',
    category: 'dessert',
    prepTime: 12,
    dietary: ['vegetarian'],
    spiceLevel: 0,
    available: true,
  },
  {
    id: '26',
    name: 'Crème Brûlée',
    description: 'Classic vanilla bean crème brûlée with caramelized sugar crust',
    price: 10,
    image: '/menu-items/creme-brulee.png',
    category: 'dessert',
    prepTime: 5,
    dietary: ['vegetarian', 'gluten-free'],
    spiceLevel: 0,
    available: true,
  },
  {
    id: '27',
    name: 'Silky Panna Cotta',
    description: 'Vanilla panna cotta with fresh berries and berry coulis',
    price: 11,
    image: '/menu-items/panna-cotta.png',
    category: 'dessert',
    prepTime: 5,
    dietary: ['vegetarian', 'gluten-free'],
    spiceLevel: 0,
    available: true,
  },
  {
    id: '28',
    name: 'Rich Chocolate Mousse',
    description: 'Dark chocolate mousse with gold leaf and cocoa powder',
    price: 10,
    image: '/menu-items/chocolate-mousse.png',
    category: 'dessert',
    prepTime: 5,
    dietary: ['vegetarian', 'gluten-free'],
    spiceLevel: 0,
    available: true,
  },
  {
    id: '29',
    name: 'New York Cheesecake',
    description: 'With dark chocolate coulis and candied lemon',
    price: 11,
    image: '/menu-items/cheesecake.png',
    category: 'dessert',
    prepTime: 5,
    dietary: ['vegetarian'],
    spiceLevel: 0,
    available: true,
  },
  {
    id: '30',
    name: 'Grand Marnier Soufflé',
    description: 'With orange zest and powdered sugar',
    price: 13,
    image: '/menu-items/grand-marnier-souffle.png',
    category: 'dessert',
    prepTime: 14,
    dietary: ['vegetarian'],
    spiceLevel: 0,
    available: true,
  },
  {
    id: '31',
    name: 'Seasonal Fruit Tart',
    description: 'With pastry cream, fresh berries, and apricot glaze',
    price: 12,
    image: '/menu-items/fruit-tart.png',
    category: 'dessert',
    prepTime: 5,
    dietary: ['vegetarian'],
    spiceLevel: 0,
    available: true,
  },
  {
    id: '32',
    name: 'Gourmet Dessert Tasting',
    description: 'Selection of macarons, chocolate bonbons, and miniature pastries',
    price: 18,
    image: '/menu-items/tasting-desserts.png',
    category: 'dessert',
    prepTime: 8,
    dietary: ['vegetarian'],
    spiceLevel: 0,
    available: true,
  },

  // Beverages
  {
    id: '33',
    name: 'Espresso Martini',
    description: 'Vodka, Kahlúa, and fresh espresso, topped with creamy foam',
    price: 14,
    image: '/menu-items/espresso-martini.png',
    category: 'beverage',
    prepTime: 3,
    dietary: ['vegan', 'gluten-free'],
    spiceLevel: 0,
    available: true,
  },
  {
    id: '34',
    name: 'Classic Old Fashioned',
    description: 'Bourbon, bitters, sugar, and ice sphere',
    price: 15,
    image: '/menu-items/old-fashioned.png',
    category: 'beverage',
    prepTime: 3,
    dietary: ['vegan', 'gluten-free'],
    spiceLevel: 0,
    available: true,
  },
  {
    id: '35',
    name: 'Premium Wine Selection',
    description: 'Curated selection of fine wines from around the world',
    price: 12,
    image: '/menu-items/wine-selection.png',
    category: 'beverage',
    prepTime: 2,
    dietary: ['vegan', 'gluten-free'],
    spiceLevel: 0,
    available: true,
  },
];
